### ISSUE TITLE
Chinese characters displayed as "\u" in Xshell.

### ISSUE THREAD

**Issue by sainnve** [rfivet/uemacs#1]
![Untitled-1](https://user-images.githubusercontent.com/43519709/147382783-731f463c-d4eb-40f7-9a8d-0c097daeac71.png)
Chinese characters displayed as "\u" in Xshell.

**Comment by rfivet** [comment]
This is linked to the implementation of wcwidth() and value of $LANG and $LC_CTYPE in your environment. Hard to guess your setup based on the screenshot.
